# Generated by Django 6.0.2 on 2026-02-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('console', models.CharField(max_length=100)),
                ('owned', models.CharField(choices=[('physical', 'Físico'), ('digital', 'Digital'), ('both', 'Físico y Digital'), ('wishlist', 'Deseado')], max_length=20)),
                ('status', models.CharField(choices=[('no-played', 'No jugado'), ('playing', 'Jugando'), ('finished', 'Terminado')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
